### PR TITLE
feat: bump to kubo 16 & libp2p 23

### PR DESCRIPTION
**Pull request by gfanton**

### CODE REVIEW

**Comment by jefft0** [comment]
`make test_bridge.android` fails for testConfig:
https://github.com/ipfs-shipyard/gomobile-ipfs/blob/bfae0f1839effb83317d6780140a61a28d350506/android/bridge/src/androidTest/java/ipfs/gomobile/android/configIPFSTests.java#L96-L99

Maybe the new version of Kubo changes the config format. For example, the original config in `backup` has:

    {"MDNS":{"Enabled":true}}

After the tests, the config has:

    {"MDNS":{"Enabled":true,"Interval":10}}

Do we need to update testConfig so that the config in `backup` has all the parameters?

**Comment by jefft0** [comment]
With go 1.17, `make build_core.android` gives the following error. Are we dropping support for go 1.17?

     # github.com/libp2p/go-libp2p-routing-helpers
    ../pkg/mod/github.com/libp2p/go-libp2p-routing-helpers@v0.4.0/compparallel.go:139:29: syntax error: unexpected [, expecting (
    ../pkg/mod/github.com/libp2p/go-libp2p-routing-helpers@v0.4.0/compparallel.go:142:43: method has multiple receivers
    ../pkg/mod/github.com/libp2p/go-libp2p-routing-helpers@v0.4.0/compparallel.go:142:43: syntax error: unexpected (, expecting name or (
    ../pkg/mod/github.com/libp2p/go-libp2p-routing-helpers@v0.4.0/compparallel.go:143:24: syntax error: unexpected { after top level declaration
    ../pkg/mod/github.com/libp2p/go-libp2p-routing-helpers@v0.4.0/compparallel.go:151:2: syntax error: non-declaration statement outside function body
    ../pkg/mod/github.com/libp2p/go-libp2p-routing-helpers@v0.4.0/compparallel.go:153:30: syntax error: unexpected {, expecting name or (
    ../pkg/mod/github.com/libp2p/go-libp2p-routing-helpers@v0.4.0/compparallel.go:185:12: method has no receiver
    ../pkg/mod/github.com/libp2p/go-libp2p-routing-helpers@v0.4.0/compparallel.go:185:12: syntax error: unexpected {, expecting name or (
    ../pkg/mod/github.com/libp2p/go-libp2p-routing-helpers@v0.4.0/compparallel.go:250:31: syntax error: unexpected [, expecting (
    ../pkg/mod/github.com/libp2p/go-libp2p-routing-helpers@v0.4.0/compparallel.go:253:43: method has multiple receivers
    ../pkg/mod/github.com/libp2p/go-libp2p-routing-helpers@v0.4.0/compparallel.go:253:43: too many errors
    note: module requires Go 1.18

**Comment by gfanton** [comment]
yes, we can **drop** support of `go-1.17`, the minimal required version is marked at the top of the `go.mod` and generally I try to stick with the version from ipfs [go.mod](https://github.com/ipfs/kubo/blob/master/go.mod#L258)

**Comment by jefft0** [comment]
@gfanton: By the way, the Java Lint error is fixed by this commit:
https://github.com/ipfs-shipyard/gomobile-ipfs/pull/144/commits/be2432f8c81721ffcabf1e30b9b702594be5bf1a

**Review by jefft0 — APPROVED** [review]

**Pull request merged**
