### PR TITLE
WIP - react-native module

### PR DESCRIPTION
**Pull request by n0izn0iz**
This alpha version has been published to npm if you want to try it out: https://www.npmjs.com/package/react-native-go-ipfs

It doesn't use the request builder so the api will very likely change

The package is 180MB compressed because the native libs are pushed to npm, this will also very likely change

Depends on first version

### CODE REVIEW

**Comment by moul** [comment]
@n0izn0iz can you rebase this branch to make it easier to review and discuss? thx

**Comment by n0izn0iz** [comment]
Behold the power of infinite commits:
Screenshot from 2020-01-30 12-47-32

Seriously tho, I just rebased, there shouldn't be a conflict, I think the repo move broke the PR, might have to reopen it.

**Comment by n0izn0iz** [comment]
Recreated here #25 for cause of broken github

**Comment by n0izn0iz** [comment]
Weird, seems it fixed itself now o.O

**Pull request closed without merging**
